
website:
  urls: https://www.hays.de/jobsuche/stellenangebote-jobs/p/1?q=Javascript&e=false&pt=false,https://www.computerfutures.com/de-de/stellensuche/?country=Deutschland&searchRadius=50km&keywords=Javascript