
website:
  urls: https://ikman.lk/en/ads/sri-lanka/vehicles?sort=relevance&buy_now=0&urgent=0&query=,https://www.computerfutures.com/de-de/stellensuche/?country=Deutschland&searchRadius=50km&keywords=Javascript